### ISSUE TITLE
searhName()

### ISSUE THREAD

**Issue by DavidK97** [DavidK97/SP3#4]
Metoden skal laves om så man søger i allMedia ArrayListen og derefter skal man promptes med et valg om man vil se filmen/serien eller gemte den til savedMedia

**Comment by lkilu6456546** [comment]
Hello, I tried to solve the issue.

This is what I did:

Modified the searchName() method to search in allMedia ArrayList and prompt user to watch or save media. Added helper methods for displaying media details and handling user choice.

You can review changes in this commit: https://github.com/lkilu6456546/DavidK97-SP3-4/commit/0b0b2a855dba071d263e2dceda3d7dc785b0dfa8.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
